# Generated by Django 5.1 on 2025-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
