# Generated by Django 5.1 on 2025-05-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.class'),
        ),
        migrations.AlterField(
            model_name='classbooking',
            name='gym_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.gymmember'),
        ),
    ]
