# Generated by Django 5.1 on 2025-05-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_classbooking_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='class_date',
            field=models.DateField(null=True),
        ),
    ]
