# Generated by Django 5.1 on 2025-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gymmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='training_area',
        ),
        migrations.AlterField(
            model_name='class',
            name='colour_hex',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='GymTrainingArea',
        ),
    ]
