# Generated by Django 5.1 on 2025-09-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_class_training_area_alter_class_colour_hex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='notes',
            new_name='description',
        ),
    ]
