# Generated by Django 5.1 on 2025-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_notes_class_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='coach',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
