# Generated by Django 5.1 on 2025-10-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gym_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.class'),
        ),
    ]
